global:
  scrape_interval:     10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# note: localhost, 127.0.0.1 or 0.0.0.0 wont work due to docker network ingress limitation
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['35.244.50.38:9091']
